typography_spectrum: 0.13151913322508335
color:
  brandStrength: 0.30906536406837404
  lightness: 0.23498352291062474
  saturation: 0.5957954949699342
  rhythmicContrast: 0.24268333637155592
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
layout_spectrum: 0.30727777536958456
author:
  name: Ed Leighton-Dick
  email: ed@leightondick.com
  url: 'http://edleightondick.com'
name: select *
navigation:
  - name: My Blog
    url: 'http://edleightondick.com'
    type: external
  - name: My Company
    url: 'http://kingfisherdata.com'
    type: external
